function [fitresult, gof] = createFit(tt, xx)
%CREATEFIT(TT,XX)
%  Create a fit.
%
%  Data for 'testx' fit:
%      X Input : tt
%      Y Output: xx
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 21-Jan-2019 17:07:05


%% Fit: 'testx'.
[xData, yData] = prepareCurveData( tt, xx );

% Set up fittype and options.
ft = 'pchipinterp';

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, 'Normalize', 'on' );

% Plot fit with data.
figure( 'Name', 'testx' );
h = plot( fitresult, xData, yData );
legend( h, 'xx vs. tt', 'testx', 'Location', 'NorthEast' );
% Label axes
xlabel tt
ylabel xx
grid on


